//======================================================================
//
// Copyright    2009 Chi Mei Communication Systems, Inc
//                                                                      
//----------------------------------------------------------------------
// PROJECT : FXX
// MODIFY BY : JamesKCTung
// MODIFY DATE : 2009, 12, 25
// CREATED BY : Will Chen
// CREATED DATE : 2008,06,21
//----------------------------------------------------------------------
//
// PURPOSE : Provides debug macros for other components, pair with library "kernel"
//

enum{
    FIH_DEBUG_ZONE_G0  = 1U << 0,
    FIH_DEBUG_ZONE_G1  = 1U << 1,
    FIH_DEBUG_ZONE_G2  = 1U << 2,
    FIH_DEBUG_ZONE_G3  = 1U << 3,
    FIH_DEBUG_ZONE_G4  = 1U << 4,
    FIH_DEBUG_ZONE_G5  = 1U << 5,
    FIH_DEBUG_ZONE_G6  = 1U << 6,
    FIH_DEBUG_ZONE_G7  = 1U << 7,
    FIH_DEBUG_ZONE_G8  = 1U << 8,
    FIH_DEBUG_ZONE_G9  = 1U << 9,
    FIH_DEBUG_ZONE_G10 = 1U << 10,
    FIH_DEBUG_ZONE_G11 = 1U << 11,
    FIH_DEBUG_ZONE_G12 = 1U << 12,
    FIH_DEBUG_ZONE_G13 = 1U << 13,
    FIH_DEBUG_ZONE_G14 = 1U << 14,
    FIH_DEBUG_ZONE_G15 = 1U << 15,
    FIH_DEBUG_ZONE_G16 = 1U << 16,
    FIH_DEBUG_ZONE_G17 = 1U << 17,
    FIH_DEBUG_ZONE_G18 = 1U << 18,
    FIH_DEBUG_ZONE_G19 = 1U << 19,
    FIH_DEBUG_ZONE_G20 = 1U << 20,
    FIH_DEBUG_ZONE_G21 = 1U << 21,
    FIH_DEBUG_ZONE_G22 = 1U << 22,
    FIH_DEBUG_ZONE_G23 = 1U << 23,
    FIH_DEBUG_ZONE_G24 = 1U << 24,
    FIH_DEBUG_ZONE_G25 = 1U << 25,
    FIH_DEBUG_ZONE_G26 = 1U << 26,
    FIH_DEBUG_ZONE_G27 = 1U << 27,
    FIH_DEBUG_ZONE_G28 = 1U << 28,
    FIH_DEBUG_ZONE_G29 = 1U << 29,
    FIH_DEBUG_ZONE_G30 = 1U << 30,
    FIH_DEBUG_ZONE_G31 = 1U << 31,
};

/* FIH;Tiger;2010/3/24 { */
#ifdef CONFIG_FIH_FXX
#define DEBUG_MASK_BASE            (MSM_PLOG_BASE2 + 0XFF000)
#else
#define DEBUG_MASK_BASE            (MSM_PLOG_BASE + 0X80000)
#endif
/* } FIH;Tiger;2010/3/24 */

#define ALS_DEBUG_MASK_OFFSET      (DEBUG_MASK_BASE)
#define VB_DEBUG_MASK_OFFSET       (ALS_DEBUG_MASK_OFFSET + 4)
#define BT_DEBUG_MASK_OFFSET       (VB_DEBUG_MASK_OFFSET + 4)
#define WIFI_DEBUG_MASK_OFFSET     (BT_DEBUG_MASK_OFFSET + 4)
#define GS_DEBUG_MASK_OFFSET       (WIFI_DEBUG_MASK_OFFSET + 4)
#define UFN_DEBUG_MASK_OFFSET      (GS_DEBUG_MASK_OFFSET + 4)
#define SER_DEBUG_MASK_OFFSET      (UFN_DEBUG_MASK_OFFSET + 4)
#define CAM_DEBUG_MASK_OFFSET      (SER_DEBUG_MASK_OFFSET + 4)
#define SD_DEBUG_MASK_OFFSET       (CAM_DEBUG_MASK_OFFSET + 4)
#define KPD_DEBUG_MASK_OFFSET      (SD_DEBUG_MASK_OFFSET + 4)
#define TOUCH_DEBUG_MASK_OFFSET    (KPD_DEBUG_MASK_OFFSET + 4)
#define LCD_DEBUG_MASK_OFFSET      (TOUCH_DEBUG_MASK_OFFSET + 4)
#define BKL_DEBUG_MASK_OFFSET      (LCD_DEBUG_MASK_OFFSET + 4)
#define PWR_DEBUG_MASK_OFFSET      (BKL_DEBUG_MASK_OFFSET + 4)
#define WAV_DEBUG_MASK_OFFSET      (PWR_DEBUG_MASK_OFFSET + 4)
#define NAND_DEBUG_MASK_OFFSET     (WAV_DEBUG_MASK_OFFSET + 4)
#define BAT_DEBUG_MASK_OFFSET      (NAND_DEBUG_MASK_OFFSET + 4)
#define NLED_DEBUG_MASK_OFFSET     (BAT_DEBUG_MASK_OFFSET + 4)
#define ECP_DEBUG_MASK_OFFSET      (NLED_DEBUG_MASK_OFFSET + 4)
#define MTB_DEBUG_MASK_OFFSET      (ECP_DEBUG_MASK_OFFSET + 4)
#define DCVS_DEBUG_MASK_OFFSET     (MTB_DEBUG_MASK_OFFSET + 4)
#define DIAGCHAR_DEBUG_MASK_OFFSET (DCVS_DEBUG_MASK_OFFSET + 4)
#define MSMRTC_DEBUG_MASK_OFFSET   (DIAGCHAR_DEBUG_MASK_OFFSET + 4)
#define ALARM_DEBUG_MASK_OFFSET    (MSMRTC_DEBUG_MASK_OFFSET + 4)

asmlinkage int fih_printk(uint32_t value, int cond, const char *fmt, ...);
//#define FIH_DEBUG_MASK(value, cond,fmt, args...) if(value & cond) {printk(fmt, ##args);}

/*#ifdef CONFIG_PRINTK
#ifdef __cplusplus
extern "C" {
#endif

#define CMDBG_FIRST_MODULE 0x00000
#define CMDBG_NEXT_MODULE 0x00100
#define CMDBG_ZONE_G0 0x00001
#define CMDBG_ZONE_G1 0x00002
#define CMDBG_ZONE_G2 0x00004
#define CMDBG_ZONE_G3 0x00008
#define CMDBG_ZONE_G4 0x00010
#define CMDBG_ZONE_G5 0x00020
#define CMDBG_ZONE_G6 0x00040

#define CMDBG_ALS1 CMDBG_FIRST_MODULE//0x00000
#define ALS1_G0 CMDBG_ALS1 + CMDBG_ZONE_G0
#define ALS1_G1 CMDBG_ALS1 + CMDBG_ZONE_G1
#define ALS1_G2 CMDBG_ALS1 + CMDBG_ZONE_G2
#define ALS1_G3 CMDBG_ALS1 + CMDBG_ZONE_G3
#define ALS1_G4 CMDBG_ALS1 + CMDBG_ZONE_G4
#define ALS1_G5 CMDBG_ALS1 + CMDBG_ZONE_G5
#define ALS1_G6 CMDBG_ALS1 + CMDBG_ZONE_G6

#define CMDBG_ALS2 CMDBG_ALS1 + CMDBG_NEXT_MODULE//0x00100
#define ALS2_G0 CMDBG_ALS2 + CMDBG_ZONE_G0
#define ALS2_G1 CMDBG_ALS2 + CMDBG_ZONE_G1
#define ALS2_G2 CMDBG_ALS2 + CMDBG_ZONE_G2
#define ALS2_G3 CMDBG_ALS2 + CMDBG_ZONE_G3
#define ALS2_G4 CMDBG_ALS2 + CMDBG_ZONE_G4
#define ALS2_G5 CMDBG_ALS2 + CMDBG_ZONE_G5
#define ALS2_G6 CMDBG_ALS2 + CMDBG_ZONE_G6

#define CMDBG_PS1 CMDBG_ALS2 + CMDBG_NEXT_MODULE//0x00200
#define PS1_G0 CMDBG_PS1 + CMDBG_ZONE_G0
#define PS1_G1 CMDBG_PS1 + CMDBG_ZONE_G1
#define PS1_G2 CMDBG_PS1 + CMDBG_ZONE_G2
#define PS1_G3 CMDBG_PS1 + CMDBG_ZONE_G3
#define PS1_G4 CMDBG_PS1 + CMDBG_ZONE_G4
#define PS1_G5 CMDBG_PS1 + CMDBG_ZONE_G5
#define PS1_G6 CMDBG_PS1 + CMDBG_ZONE_G6

#define CMDBG_PS2 CMDBG_PS1 + CMDBG_NEXT_MODULE//0x00300
#define PS2_G0 CMDBG_PS2 + CMDBG_ZONE_G0
#define PS2_G1 CMDBG_PS2 + CMDBG_ZONE_G1
#define PS2_G2 CMDBG_PS2 + CMDBG_ZONE_G2
#define PS2_G3 CMDBG_PS2 + CMDBG_ZONE_G3
#define PS2_G4 CMDBG_PS2 + CMDBG_ZONE_G4
#define PS2_G5 CMDBG_PS2 + CMDBG_ZONE_G5
#define PS2_G6 CMDBG_PS2 + CMDBG_ZONE_G6

#define CMDBG_VB1 CMDBG_PS2 + CMDBG_NEXT_MODULE//0x00400
#define VB1_G0 CMDBG_VB1 + CMDBG_ZONE_G0
#define VB1_G1 CMDBG_VB1 + CMDBG_ZONE_G1
#define VB1_G2 CMDBG_VB1 + CMDBG_ZONE_G2
#define VB1_G3 CMDBG_VB1 + CMDBG_ZONE_G3
#define VB1_G4 CMDBG_VB1 + CMDBG_ZONE_G4
#define VB1_G5 CMDBG_VB1 + CMDBG_ZONE_G5
#define VB1_G6 CMDBG_VB1 + CMDBG_ZONE_G6

#define CMDBG_VB2 CMDBG_VB1 + CMDBG_NEXT_MODULE//0x00500
#define VB2_G0 CMDBG_VB2 + CMDBG_ZONE_G0
#define VB2_G1 CMDBG_VB2 + CMDBG_ZONE_G1
#define VB2_G2 CMDBG_VB2 + CMDBG_ZONE_G2
#define VB2_G3 CMDBG_VB2 + CMDBG_ZONE_G3
#define VB2_G4 CMDBG_VB2 + CMDBG_ZONE_G4
#define VB2_G5 CMDBG_VB2 + CMDBG_ZONE_G5
#define VB2_G6 CMDBG_VB2 + CMDBG_ZONE_G6

#define CMDBG_BT1 CMDBG_VB2 + CMDBG_NEXT_MODULE//0x00600
#define BT1_G0 CMDBG_BT1 + CMDBG_ZONE_G0
#define BT1_G1 CMDBG_BT1 + CMDBG_ZONE_G1
#define BT1_G2 CMDBG_BT1 + CMDBG_ZONE_G2
#define BT1_G3 CMDBG_BT1 + CMDBG_ZONE_G3
#define BT1_G4 CMDBG_BT1 + CMDBG_ZONE_G4
#define BT1_G5 CMDBG_BT1 + CMDBG_ZONE_G5
#define BT1_G6 CMDBG_BT1 + CMDBG_ZONE_G6

#define CMDBG_BT2 CMDBG_BT1 + CMDBG_NEXT_MODULE//0x00700
#define BT2_G0 CMDBG_BT2 + CMDBG_ZONE_G0
#define BT2_G1 CMDBG_BT2 + CMDBG_ZONE_G1
#define BT2_G2 CMDBG_BT2 + CMDBG_ZONE_G2
#define BT2_G3 CMDBG_BT2 + CMDBG_ZONE_G3
#define BT2_G4 CMDBG_BT2 + CMDBG_ZONE_G4
#define BT2_G5 CMDBG_BT2 + CMDBG_ZONE_G5
#define BT2_G6 CMDBG_BT2 + CMDBG_ZONE_G6

#define CMDBG_BT3 CMDBG_BT2 + CMDBG_NEXT_MODULE//0x00800
#define BT3_G0 CMDBG_BT3 + CMDBG_ZONE_G0
#define BT3_G1 CMDBG_BT3 + CMDBG_ZONE_G1
#define BT3_G2 CMDBG_BT3 + CMDBG_ZONE_G2
#define BT3_G3 CMDBG_BT3 + CMDBG_ZONE_G3
#define BT3_G4 CMDBG_BT3 + CMDBG_ZONE_G4
#define BT3_G5 CMDBG_BT3 + CMDBG_ZONE_G5
#define BT3_G6 CMDBG_BT3 + CMDBG_ZONE_G6

#define CMDBG_BT4 CMDBG_BT3 + CMDBG_NEXT_MODULE//0x00900
#define BT4_G0 CMDBG_BT4 + CMDBG_ZONE_G0
#define BT4_G1 CMDBG_BT4 + CMDBG_ZONE_G1
#define BT4_G2 CMDBG_BT4 + CMDBG_ZONE_G2
#define BT4_G3 CMDBG_BT4 + CMDBG_ZONE_G3
#define BT4_G4 CMDBG_BT4 + CMDBG_ZONE_G4
#define BT4_G5 CMDBG_BT4 + CMDBG_ZONE_G5
#define BT4_G6 CMDBG_BT4 + CMDBG_ZONE_G6

#define CMDBG_WIFI CMDBG_BT4 + CMDBG_NEXT_MODULE//0x00A00
#define WIFI_G0 CMDBG_WIFI + CMDBG_ZONE_G0
#define WIFI_G1 CMDBG_WIFI + CMDBG_ZONE_G1
#define WIFI_G2 CMDBG_WIFI + CMDBG_ZONE_G2
#define WIFI_G3 CMDBG_WIFI + CMDBG_ZONE_G3
#define WIFI_G4 CMDBG_WIFI + CMDBG_ZONE_G4
#define WIFI_G5 CMDBG_WIFI + CMDBG_ZONE_G5
#define WIFI_G6 CMDBG_WIFI + CMDBG_ZONE_G6

#define CMDBG_WIFI2 CMDBG_WIFI + CMDBG_NEXT_MODULE//0x00B00
#define WIFI2_G0 CMDBG_WIFI2 + CMDBG_ZONE_G0
#define WIFI2_G1 CMDBG_WIFI2 + CMDBG_ZONE_G1
#define WIFI2_G2 CMDBG_WIFI2 + CMDBG_ZONE_G2
#define WIFI2_G3 CMDBG_WIFI2 + CMDBG_ZONE_G3
#define WIFI2_G4 CMDBG_WIFI2 + CMDBG_ZONE_G4
#define WIFI2_G5 CMDBG_WIFI2 + CMDBG_ZONE_G5
#define WIFI2_G6 CMDBG_WIFI2 + CMDBG_ZONE_G6

#define CMDBG_GPS CMDBG_BT2 + CMDBG_NEXT_MODULE//0x00C00
#define GPS_G0 CMDBG_GPS + CMDBG_ZONE_G0
#define GPS_G1 CMDBG_GPS + CMDBG_ZONE_G1
#define GPS_G2 CMDBG_GPS + CMDBG_ZONE_G2
#define GPS_G3 CMDBG_GPS + CMDBG_ZONE_G3
#define GPS_G4 CMDBG_GPS + CMDBG_ZONE_G4
#define GPS_G5 CMDBG_GPS + CMDBG_ZONE_G5
#define GPS_G6 CMDBG_GPS + CMDBG_ZONE_G6
//Debug zone (cond) definition : Wireless -

//Debug zone (cond) definition : Peripheral +
#define CMDBG_GS CMDBG_GPS + CMDBG_NEXT_MODULE//0x00D00
#define GS_G0 CMDBG_GS + CMDBG_ZONE_G0
#define GS_G1 CMDBG_GS + CMDBG_ZONE_G1
#define GS_G2 CMDBG_GS + CMDBG_ZONE_G2
#define GS_G3 CMDBG_GS + CMDBG_ZONE_G3
#define GS_G4 CMDBG_GS + CMDBG_ZONE_G4
#define GS_G5 CMDBG_GS + CMDBG_ZONE_G5
#define GS_G6 CMDBG_GS + CMDBG_ZONE_G6

#define CMDBG_UFN CMDBG_GS + CMDBG_NEXT_MODULE//0x00E00
#define UFN_G0 CMDBG_UFN + CMDBG_ZONE_G0
#define UFN_G1 CMDBG_UFN + CMDBG_ZONE_G1
#define UFN_G2 CMDBG_UFN + CMDBG_ZONE_G2
#define UFN_G3 CMDBG_UFN + CMDBG_ZONE_G3
#define UFN_G4 CMDBG_UFN + CMDBG_ZONE_G4
#define UFN_G5 CMDBG_UFN + CMDBG_ZONE_G5
#define UFN_G6 CMDBG_UFN + CMDBG_ZONE_G6

#define CMDBG_RNDIS CMDBG_UFN + CMDBG_NEXT_MODULE//0x00F00
#define RNDIS_G0 CMDBG_RNDIS + CMDBG_ZONE_G0
#define RNDIS_G1 CMDBG_RNDIS + CMDBG_ZONE_G1
#define RNDIS_G2 CMDBG_RNDIS + CMDBG_ZONE_G2
#define RNDIS_G3 CMDBG_RNDIS + CMDBG_ZONE_G3
#define RNDIS_G4 CMDBG_RNDIS + CMDBG_ZONE_G4
#define RNDIS_G5 CMDBG_RNDIS + CMDBG_ZONE_G5
#define RNDIS_G6 CMDBG_RNDIS + CMDBG_ZONE_G6

#define CMDBG_STOR CMDBG_RNDIS + CMDBG_NEXT_MODULE//0x01000
#define STOR_G0 CMDBG_STOR + CMDBG_ZONE_G0
#define STOR_G1 CMDBG_STOR + CMDBG_ZONE_G1
#define STOR_G2 CMDBG_STOR + CMDBG_ZONE_G2
#define STOR_G3 CMDBG_STOR + CMDBG_ZONE_G3
#define STOR_G4 CMDBG_STOR + CMDBG_ZONE_G4
#define STOR_G5 CMDBG_STOR + CMDBG_ZONE_G5
#define STOR_G6 CMDBG_STOR + CMDBG_ZONE_G6

#define CMDBG_SER CMDBG_STOR + CMDBG_NEXT_MODULE//0x01100
#define SER_G0 CMDBG_SER + CMDBG_ZONE_G0
#define SER_G1 CMDBG_SER + CMDBG_ZONE_G1
#define SER_G2 CMDBG_SER + CMDBG_ZONE_G2
#define SER_G3 CMDBG_SER + CMDBG_ZONE_G3
#define SER_G4 CMDBG_SER + CMDBG_ZONE_G4
#define SER_G5 CMDBG_SER + CMDBG_ZONE_G5
#define SER_G6 CMDBG_SER + CMDBG_ZONE_G6

#define CMDBG_CAM CMDBG_SER + CMDBG_NEXT_MODULE//0x01200
#define CAM_G0 CMDBG_CAM + CMDBG_ZONE_G0
#define CAM_G1 CMDBG_CAM + CMDBG_ZONE_G1
#define CAM_G2 CMDBG_CAM + CMDBG_ZONE_G2
#define CAM_G3 CMDBG_CAM + CMDBG_ZONE_G3
#define CAM_G4 CMDBG_CAM + CMDBG_ZONE_G4
#define CAM_G5 CMDBG_CAM + CMDBG_ZONE_G5
#define CAM_G6 CMDBG_CAM + CMDBG_ZONE_G6

#define CMDBG_SD CMDBG_CAM + CMDBG_NEXT_MODULE//0x01300
#define SD_G0 CMDBG_SD + CMDBG_ZONE_G0
#define SD_G1 CMDBG_SD + CMDBG_ZONE_G1
#define SD_G2 CMDBG_SD + CMDBG_ZONE_G2
#define SD_G3 CMDBG_SD + CMDBG_ZONE_G3
#define SD_G4 CMDBG_SD + CMDBG_ZONE_G4
#define SD_G5 CMDBG_SD + CMDBG_ZONE_G5
#define SD_G6 CMDBG_SD + CMDBG_ZONE_G6

#define CMDBG_SD2 CMDBG_SD + CMDBG_NEXT_MODULE//0x01400
#define SD2_G0 CMDBG_SD2 + CMDBG_ZONE_G0
#define SD2_G1 CMDBG_SD2 + CMDBG_ZONE_G1
#define SD2_G2 CMDBG_SD2 + CMDBG_ZONE_G2
#define SD2_G3 CMDBG_SD2 + CMDBG_ZONE_G3
#define SD2_G4 CMDBG_SD2 + CMDBG_ZONE_G4
#define SD2_G5 CMDBG_SD2 + CMDBG_ZONE_G5
#define SD2_G6 CMDBG_SD2 + CMDBG_ZONE_G6
//Debug zone (cond) definition : Peripheral -

//Debug zone (cond) definition : System +
#define CMDBG_KPD CMDBG_SD2 + CMDBG_NEXT_MODULE//0x01500
#define KPD_G0 CMDBG_KPD + CMDBG_ZONE_G0
#define KPD_G1 CMDBG_KPD + CMDBG_ZONE_G1
#define KPD_G2 CMDBG_KPD + CMDBG_ZONE_G2
#define KPD_G3 CMDBG_KPD + CMDBG_ZONE_G3
#define KPD_G4 CMDBG_KPD + CMDBG_ZONE_G4
#define KPD_G5 CMDBG_KPD + CMDBG_ZONE_G5
#define KPD_G6 CMDBG_KPD + CMDBG_ZONE_G6

#define CMDBG_TOUCH CMDBG_KPD + CMDBG_NEXT_MODULE//0x01600
#define TOUCH_G0 CMDBG_TOUCH + CMDBG_ZONE_G0
#define TOUCH_G1 CMDBG_TOUCH + CMDBG_ZONE_G1
#define TOUCH_G2 CMDBG_TOUCH + CMDBG_ZONE_G2
#define TOUCH_G3 CMDBG_TOUCH + CMDBG_ZONE_G3
#define TOUCH_G4 CMDBG_TOUCH + CMDBG_ZONE_G4
#define TOUCH_G5 CMDBG_TOUCH + CMDBG_ZONE_G5
#define TOUCH_G6 CMDBG_TOUCH + CMDBG_ZONE_G6

#define CMDBG_LCD CMDBG_TOUCH + CMDBG_NEXT_MODULE//0x01700
#define LCD_G0 CMDBG_LCD + CMDBG_ZONE_G0
#define LCD_G1 CMDBG_LCD + CMDBG_ZONE_G1
#define LCD_G2 CMDBG_LCD + CMDBG_ZONE_G2
#define LCD_G3 CMDBG_LCD + CMDBG_ZONE_G3
#define LCD_G4 CMDBG_LCD + CMDBG_ZONE_G4
#define LCD_G5 CMDBG_LCD + CMDBG_ZONE_G5
#define LCD_G6 CMDBG_LCD + CMDBG_ZONE_G6

#define CMDBG_BKL CMDBG_LCD + CMDBG_NEXT_MODULE//0x01800
#define BKL_G0 CMDBG_BKL + CMDBG_ZONE_G0
#define BKL_G1 CMDBG_BKL + CMDBG_ZONE_G1
#define BKL_G2 CMDBG_BKL + CMDBG_ZONE_G2
#define BKL_G3 CMDBG_BKL + CMDBG_ZONE_G3
#define BKL_G4 CMDBG_BKL + CMDBG_ZONE_G4
#define BKL_G5 CMDBG_BKL + CMDBG_ZONE_G5
#define BKL_G6 CMDBG_BKL + CMDBG_ZONE_G6

#define CMDBG_PWR CMDBG_BKL + CMDBG_NEXT_MODULE//0x01900
#define PWR_G0 CMDBG_PWR + CMDBG_ZONE_G0
#define PWR_G1 CMDBG_PWR + CMDBG_ZONE_G1
#define PWR_G2 CMDBG_PWR + CMDBG_ZONE_G2
#define PWR_G3 CMDBG_PWR + CMDBG_ZONE_G3
#define PWR_G4 CMDBG_PWR + CMDBG_ZONE_G4
#define PWR_G5 CMDBG_PWR + CMDBG_ZONE_G5
#define PWR_G6 CMDBG_PWR + CMDBG_ZONE_G6

#define CMDBG_WAV CMDBG_PWR + CMDBG_NEXT_MODULE//0x01A00
#define WAV_G0 CMDBG_WAV + CMDBG_ZONE_G0
#define WAV_G1 CMDBG_WAV + CMDBG_ZONE_G1
#define WAV_G2 CMDBG_WAV + CMDBG_ZONE_G2
#define WAV_G3 CMDBG_WAV + CMDBG_ZONE_G3
#define WAV_G4 CMDBG_WAV + CMDBG_ZONE_G4
#define WAV_G5 CMDBG_WAV + CMDBG_ZONE_G5
#define WAV_G6 CMDBG_WAV + CMDBG_ZONE_G6

#define CMDBG_WAV2 CMDBG_WAV + CMDBG_NEXT_MODULE//0x01B00
#define WAV2_G0 CMDBG_WAV2 + CMDBG_ZONE_G0
#define WAV2_G1 CMDBG_WAV2 + CMDBG_ZONE_G1
#define WAV2_G2 CMDBG_WAV2 + CMDBG_ZONE_G2
#define WAV2_G3 CMDBG_WAV2 + CMDBG_ZONE_G3
#define WAV2_G4 CMDBG_WAV2 + CMDBG_ZONE_G4
#define WAV2_G5 CMDBG_WAV2 + CMDBG_ZONE_G5
#define WAV2_G6 CMDBG_WAV2 + CMDBG_ZONE_G6

#define CMDBG_FMD CMDBG_WAV2 + CMDBG_NEXT_MODULE//0x01C00
#define FMD_G0 CMDBG_FMD + CMDBG_ZONE_G0
#define FMD_G1 CMDBG_FMD + CMDBG_ZONE_G1
#define FMD_G2 CMDBG_FMD + CMDBG_ZONE_G2
#define FMD_G3 CMDBG_FMD + CMDBG_ZONE_G3
#define FMD_G4 CMDBG_FMD + CMDBG_ZONE_G4
#define FMD_G5 CMDBG_FMD + CMDBG_ZONE_G5
#define FMD_G6 CMDBG_FMD + CMDBG_ZONE_G6

#define CMDBG_BAT CMDBG_FMD + CMDBG_NEXT_MODULE//0x01D00
#define BAT_G0 CMDBG_BAT + CMDBG_ZONE_G0
#define BAT_G1 CMDBG_BAT + CMDBG_ZONE_G1
#define BAT_G2 CMDBG_BAT + CMDBG_ZONE_G2
#define BAT_G3 CMDBG_BAT + CMDBG_ZONE_G3
#define BAT_G4 CMDBG_BAT + CMDBG_ZONE_G4
#define BAT_G5 CMDBG_BAT + CMDBG_ZONE_G5
#define BAT_G6 CMDBG_BAT + CMDBG_ZONE_G6

#define CMDBG_NLED CMDBG_BAT + CMDBG_NEXT_MODULE//0x01E00
#define NLED_G0 CMDBG_NLED + CMDBG_ZONE_G0
#define NLED_G1 CMDBG_NLED + CMDBG_ZONE_G1
#define NLED_G2 CMDBG_NLED + CMDBG_ZONE_G2
#define NLED_G3 CMDBG_NLED + CMDBG_ZONE_G3
#define NLED_G4 CMDBG_NLED + CMDBG_ZONE_G4
#define NLED_G5 CMDBG_NLED + CMDBG_ZONE_G5
#define NLED_G6 CMDBG_NLED + CMDBG_ZONE_G6

#define CMDBG_MTB CMDBG_NLED + CMDBG_NEXT_MODULE//0x01F00
#define MTB_G0 CMDBG_MTB + CMDBG_ZONE_G0
#define MTB_G1 CMDBG_MTB + CMDBG_ZONE_G1
#define MTB_G2 CMDBG_MTB + CMDBG_ZONE_G2
#define MTB_G3 CMDBG_MTB + CMDBG_ZONE_G3
#define MTB_G4 CMDBG_MTB + CMDBG_ZONE_G4
#define MTB_G5 CMDBG_MTB + CMDBG_ZONE_G5
#define MTB_G6 CMDBG_MTB + CMDBG_ZONE_G6
//Debug zone (cond) definition : System -

asmlinkage int fih_printk(int cond, const char *fmt, ...);

#ifdef __cplusplus
}
#endif
#else  // else CONFIG_PRINTK
#define fih_printk(x, y, ...) {}
#endif // end CONFIG_PRINTK
*/
